### ISSUE TITLE
usage of this tool

### ISSUE THREAD

**Issue by nacimgoura** [codsen/detergent#13]
Hello,
I have this sentence : ''directeur de l&#x2019;Agence Nationale de l&#x2019;Evaluation et de la qualit&#xE9; des &#xE9;tablissements et Services sociaux" and i would like this sentence "directeur de l'Agence Nationale de l'Evaluation et de la qualité des établissements et Services sociaux" but with your encoder I get this sentence : "directeur de l&rsquo;Agence Nationale de l&rsquo;Evaluation et de la qualit&eacute; des &eacute;tablissements et Services&nbsp;sociaux".
I think I use this encoder badly. What should I do to get the right sentence?

Thank you for your help :+1:

**Comment by nacimgoura** [comment]
I finally did, sorry for the inconvenience.

**Comment by revelt** [comment]
Detergent's aim is to make typography _fancy_. In your case you need the opposite, to _unfancy_. Try my other library, [https://github.com/codsen/string-unfancy](https://github.com/codsen/string-unfancy). Here's the quick test in JavaScript that does what you need: https://runkit.com/embed/6m866jv1hx4d

**Comment by revelt** [comment]
no worries 👍
