### ISSUE TITLE
add space for list li

### ISSUE THREAD

**Issue by nacimgoura** [codsen/detergent#14]
Hello,
when I use detergent with this sentence : 

```html
<ul><li><a>Accueil<div></div></a></li><li><a>Publications et outils</a><div><ul><li><a>Publications</a></li><li><a>Outils</a></li><li><a>Centre de ressources</a></li><li><a>Formations en ligne</a></li></ul>
```

the result is : `AccueilPublications et outilsPublicationsOutilsCentre de ressourcesFormations en&nbsp;ligne`.

Is it possible to add a space after each li so that the words are not pasted together ?
So the result will be: `Accueil Publications et outils Publications Outils Centre de ressources Formations en ligne`.

Also il `\n` is visible, It's not replaced by `br` if I choose replace line breaks with `br`.

Thanks you for your works :smiley:

**Comment by revelt** [comment]
hi Nacim,
Can you please put the original source code with html formatting, three backticks (\`) then followed with html, then your code, then three back ticks on a new line?
I suppose it was just a bunch of `<li>`'s?

**Comment by revelt** [comment]
Ignore that, retrieved the code from "edit" mode. Let me have a look. 

How latest do you need this?

**Comment by nacimgoura** [comment]
This is not urgent, I use your tool in a project whose words are used in a search engine. That's how I noticed that the words were stuck together.

**Comment by revelt** [comment]
Which one are you using, website (https://detergent.io) or an npm library (https://www.npmjs.com/package/detergent)?

**Comment by nacimgoura** [comment]
I use an npm library but I tryed with website also.

**Comment by revelt** [comment]
Good. I can release npm library without much hassle, but website is a bit tricky because I'm in progress recoding it and I'd rather would not touch the old code. It's got Grunt as a task runner, imagine...

**Comment by nacimgoura** [comment]
I understand, thank you very much for your help!

**Comment by revelt** [comment]
please review your code using the latest v2.30.0

**Comment by nacimgoura** [comment]
Thank you for your release, I will test.

**Comment by revelt** [comment]
I'll close now, but if you have ant issues do open a new issue. Thank you for being proactive 👍 .
