### ISSUE TITLE
remove code in <script>

### ISSUE THREAD

**Issue by nacimgoura** [codsen/detergent#15]
Hello,
thank you for your work :smile: ,
I use this script for clean HTML and encode character.
This works fine but it would be nice if it removes the code between the <script></script>.
Currently, for example with :
```
lorem ipsum...
<script>
console.log('test');
</script>
```
The result will be :
```
console.log('test');
```
I think it would be better to delete it because this is not something relevant to keep.

**Comment by revelt** [comment]
Yeah, it's doable.
I'm wondering, since we're at it, what other tags should be included in the list, to be removed together with their contents..

`form` as well maybe? It's unlikely the cleaned output would be usable anyway with all labels etc

**Comment by nacimgoura** [comment]
The <code> tag is useless too, but I get the impression that it is already removed.
Also, I have questions. 
Why remove dots from HTML content ?
Is keeping the text links really relevant?

**Comment by revelt** [comment]
What do you mean by "dots"?

**Comment by nacimgoura** [comment]
For example the script convert `adoption...` into `adoption…`
It replace `...` with an ascii character `…`.

**Comment by revelt** [comment]
yeah, it's called [ellipsis](http://practicaltypography.com/ellipses.html) - basically three dots in sequence make the gaps too small for good looking ellipsis. But if you put spaces in-between it makes the gaps too wide. Hence the use of dedicated character.

I agree, that should be customise-able, with flip switch in the options.

**Comment by nacimgoura** [comment]
Okay, I didn't know, I thought it was a bug. Thank you for telling me!

**Comment by nacimgoura** [comment]
Also, I don't know if it's worth keeping \ and /.
Is it possible to transform + into more and - into less?

**Comment by revelt** [comment]
Since these are characters, I'd rather keep on the safe side and leave them alone. The main purpose of Detergent is to prepare the text to be placed into HTML, especially email template-HTML. Now, many people use D. for wider purposes and I'm concerned tinkering with regular characters (slashes and plus/minus) might cause more harm in the long run on those cases. On normal text, copy-pasted from M$ Excel, Illustrator or Acrobat or M$ Word, such characters probably are never placed at the first place, and if they are, they are intentional.

Did you encounter use cases where slashes, pipes or plus/minus would be better removed by D.?

**Comment by nacimgoura** [comment]
No, I not encountered this cases.
I use detergent to clean HTML before indexing it with elasticsearch (https://www.elastic.co/) to allow a search on it.
And all characters like \ / + - are considered noise and make the search less relevant.
That's why I need to remove all the characters before indexing.
But detergent works perfectly, I was just looking at how to improve it.

**Comment by revelt** [comment]
I see... But then could you apply a regex `/[/\\|+-]/g` and replace all these with empty string as a second run, after D.?

**Comment by nacimgoura** [comment]
Yes, that's what I'm doing already :smile:

**Comment by nacimgoura** [comment]
Yes, that's what I'm doing already :smile:

**Comment by revelt** [comment]
:)

**Comment by revelt** [comment]
Added to 2.32.0

**Comment by nacimgoura** [comment]
Thanks :wink:
