### ISSUE TITLE
strange bug

### ISSUE THREAD

**Issue by nacimgoura** [codsen/detergent#17]
Hello,
I thinks I have encountered a strange bug.
I passed this text in this plugin : 
`fonds social européen (fse) emploi et formation département de la haute-savoie`
with this configuration :
```
detergent(text, {
            removeWidows: true,             // Replace the last space in paragraph with &nbsp;
            convertEntities: false,          // Encode all non-ASCII chars
            convertDashes: false,            // Typographically-correct the n/m-dashes
            convertApostrophes: false,       // Typographically-correct the apostrophes
            replaceLineBreaks: true,        // Replace all line breaks with BR's
            removeLineBreaks: false,        // Put everything on one line
            useXHTML: false,                 // Add closing slashes on BR's
            removeSoftHyphens: true,        // Remove character which encodes to &#173; or &shy;
            dontEncodeNonLatin: true,       // Skip non-latin character encoding
            keepBoldEtc: false,              // Any bold, strong, i or em tags are stripped of attributes and retained
            addMissingSpaces: true          // Adds missing spaces after dots/colons/semicolons, unless it's URL
        })
```
But in my units tests I compared the text before use this plugin and after and they are not equals.
I found it had a different ascii character at 65th position.

The strangest thing is that when I replace `haute-savoie` by `haute savoie`, The 65th characters is equal in two text.
My example : https://runkit.com/nacimgoura/detergent

**Comment by revelt** [comment]
It's a non-breaking space being added between last two words to prevent [widows](https://en.wikipedia.org/wiki/Widows_and_orphans). You should turn off `opts. removeWidows` if you don't want window-removal.

**Comment by revelt** [comment]
Read the readme :) No, seriously, when you replace `haute savoie` then non-breaking space is added after `haute`. I'm talking about non-encoded &nbsp; or https://unicode-table.com/en/00A0/

Please confirm can we close this issue

**Comment by nacimgoura** [comment]
Sorry I did not watch enough, it solved my problem.
