### ISSUE TITLE
Remove \u200E and \u200F?

### ISSUE THREAD

**Issue by jacksteamdev** [codsen/detergent#19]
It seems that Detergent does not remove Right-to-left and Left-to-right marks. Is this intentional? Here's a sample run through Detergent.io:

> Puro, Chile, es‎ tu cielo ‎azulado. Puras brisas te cruzan también. Y tu campo de flores bordado, es la copia feliz del Edén. Majestuosa ‎‎es la blanca montaña, que te dio por baluarte el Señor. Y ese mar ‎que tranquilo te baña, te‎‎ promete futuro esplendor.

Thanks!

**Comment by revelt** [comment]
thank you for reporting this, I'll investigate and fix asap.

**Comment by revelt** [comment]
fiy, the detergent.io front-end is a couple releases behind, I want to release it on Vue.js, it's not complete yet. API on the other hand is quick to fix and I'll update it within next few days. Hopefully the rogue marks don't cause too much problem in the meantime. Again, thanks for catching this.

**Comment by jacksteamdev** [comment]
Looks good!

**Comment by revelt** [comment]
Thank you! I was reluctant to close it until front-end was not updated but, I think it's right, it should be closed. 👍
